[project]
name = "umotion"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "autogluon>=1.3.1",
    "chumpy>=0.70",
    "loguru>=0.7.3",
    "prettytable>=3.16.0",
    "torch>=2.6.0",
    "trimesh>=4.7.1",
]
